#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot arm joints
doosan_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint1, joint2, joint3, joint4, joint5,joint6]

#Controller to control end effector joints
gripper_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [finger_joint]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
